// GENERATED by tools/importart.mjs — do not edit by hand.
//
// Source images live in art-in/. Re-import with:
//
//   node tools/importart.mjs
//
// These override both hand-authored and vector-drawn sprites of the same name.
// Empty by default: the game ships entirely on art drawn in code, and this file
// only fills up if someone drops PNGs into art-in/.

export const IMPORTED = {
};
