// PNG -> palette-locked sprite importer.
//
//   node tools/importart.mjs               import everything in art-in/
//   node tools/importart.mjs --list        print every sprite name and its size
//   node tools/importart.mjs --height 32   override the target height
//
// Drop `art-in/<spriteName>.png` and this scales it to the size the game
// already uses for that sprite, box-filters it down, and snaps every pixel to
// the game palette. Output goes to src/art/imported.js as ordinary sprite rows,
// which override both the hand-authored and the vector-drawn versions.
//
// The palette snap is the whole point. Art from different sources — a different
// tool, a different day, a different model — arrives with its own colours, its
// own anti-aliasing and its own idea of contrast. Forcing it through one
// palette is what makes a jobsite look like one jobsite instead of a collage.

import { chromium } from 'playwright';
import { writeFile, readdir, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { serve } from './serve.mjs';
import { launchOptions } from './browser.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const IN_DIR = 'art-in';
const SS_MIN = 2;        // supersample at least this much before snapping
const ALPHA_CUT = 0.45;  // below this a pixel is transparent

const args = process.argv.slice(2);
const heightArg = args.includes('--height') ? Number(args[args.indexOf('--height') + 1]) : null;

/** The shopping list: what to name a file, and how big the game draws it. */
async function list() {
  const { ART } = await import('../src/art/sprites.js');
  const { SPRITES } = await import('../src/art/names.js');
  const { IMPORTED } = await import('../src/art/imported.js');
  console.log('name                 size      file to drop in art-in/');
  for (const name of SPRITES) {
    const rows = ART[name];
    const size = rows ? `${rows[0].length}x${rows.length}` : '?';
    const mark = IMPORTED[name] ? '  <- imported' : '';
    console.log(`  ${name.padEnd(18)} ${size.padEnd(9)} ${name}.png${mark}`);
  }
  console.log('\nAspect ratio is preserved — the height is what gets matched, so a wider');
  console.log('image just draws wider. Read art-in/README.md before generating anything.');
}

/** Write src/art/imported.js, empty or otherwise. */
async function emit(sprites) {
  const body = Object.entries(sprites)
    .map(([name, rows]) => `  ${name}: [\n${rows.map((r) => `    '${r}',`).join('\n')}\n  ],`)
    .join('\n');

  await writeFile(join(ROOT, 'src/art/imported.js'), `// GENERATED by tools/importart.mjs — do not edit by hand.
//
// Source images live in art-in/. Re-import with:
//
//   node tools/importart.mjs
//
// These override both hand-authored and vector-drawn sprites of the same name.
// Empty by default: the game ships entirely on art drawn in code, and this file
// only fills up if someone drops PNGs into art-in/.

export const IMPORTED = {
${body ? `${body}\n` : ''}};
`);
}

async function main() {
  if (args.includes('--list')) return list();

  await mkdir(join(ROOT, IN_DIR), { recursive: true });
  let files = [];
  try {
    files = (await readdir(join(ROOT, IN_DIR))).filter((f) => /\.png$/i.test(f));
  } catch { /* no directory yet */ }

  if (!files.length) {
    // Still write the file. Deleting a PNG and re-running has to actually undo
    // the import, or the game keeps drawing art whose source is gone.
    await emit({});
    console.log(`nothing to import: put <spriteName>.png files in ${IN_DIR}/`);
    console.log('see art-in/README.md for what the images need to look like');
    return;
  }

  const { server, port } = await serve(0);
  const browser = await chromium.launch(launchOptions());
  const page = await browser.newPage({ viewport: { width: 800, height: 600 } });
  const errors = [];
  page.on('pageerror', (e) => errors.push(String(e.stack || e)));

  await page.goto(`http://localhost:${port}/index.html`, { waitUntil: 'load' });

  const result = await page.evaluate(async ({ dir, names, alphaCut, ssMin, forceHeight }) => {
    const { PAL, ART } = await import('/src/art/sprites.js');

    const keys = Object.keys(PAL);
    const rgb = keys.map((k) => {
      const h = PAL[k];
      return [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)];
    });
    const nearest = (r, g, b) => {
      let best = 0;
      let bestD = Infinity;
      for (let i = 0; i < rgb.length; i++) {
        const dr = (r - rgb[i][0]) * 0.5;
        const dg = (g - rgb[i][1]) * 0.7;
        const db = (b - rgb[i][2]) * 0.3;
        const d = dr * dr + dg * dg + db * db;
        if (d < bestD) { bestD = d; best = i; }
      }
      return keys[best];
    };

    const load = (src) => new Promise((res, rej) => {
      const img = new Image();
      img.onload = () => res(img);
      img.onerror = () => rej(new Error(`could not load ${src}`));
      img.src = src;
    });

    const out = {};
    const report = [];
    for (const file of names) {
      const name = file.replace(/\.png$/i, '');
      const img = await load(`/${dir}/${file}`);

      // Trim transparent margins so the artwork itself decides the bounds —
      // generated images almost always arrive with uneven padding.
      const probe = document.createElement('canvas');
      probe.width = img.naturalWidth;
      probe.height = img.naturalHeight;
      const pctx = probe.getContext('2d');
      pctx.drawImage(img, 0, 0);
      const pd = pctx.getImageData(0, 0, probe.width, probe.height).data;
      let x0 = probe.width; let y0 = probe.height; let x1 = -1; let y1 = -1;
      for (let y = 0; y < probe.height; y++) {
        for (let x = 0; x < probe.width; x++) {
          if (pd[((y * probe.width) + x) * 4 + 3] > 12) {
            if (x < x0) x0 = x;
            if (y < y0) y0 = y;
            if (x > x1) x1 = x;
            if (y > y1) y1 = y;
          }
        }
      }
      const opaque = x1 >= x0 && y1 >= y0;
      if (!opaque) { x0 = 0; y0 = 0; x1 = probe.width - 1; y1 = probe.height - 1; }
      const cropW = x1 - x0 + 1;
      const cropH = y1 - y0 + 1;

      // Target size: match what the game already uses for this sprite, so an
      // import is a drop-in replacement and nothing downstream shifts.
      const existing = ART[name];
      const targetH = forceHeight || (existing ? existing.length : 24);
      const targetW = Math.max(1, Math.round(cropW * (targetH / cropH)));

      // Draw big, then box-filter down: browser downscaling alone leaves soft
      // edges that quantise into mud.
      const ss = Math.max(ssMin, Math.ceil(64 / targetH));
      const cv = document.createElement('canvas');
      cv.width = targetW * ss;
      cv.height = targetH * ss;
      const ctx = cv.getContext('2d');
      ctx.imageSmoothingEnabled = true;
      ctx.imageSmoothingQuality = 'high';
      ctx.drawImage(img, x0, y0, cropW, cropH, 0, 0, cv.width, cv.height);

      const data = ctx.getImageData(0, 0, cv.width, cv.height).data;
      const rows = [];
      for (let y = 0; y < targetH; y++) {
        let row = '';
        for (let x = 0; x < targetW; x++) {
          let r = 0; let g = 0; let b = 0; let a = 0;
          for (let sy = 0; sy < ss; sy++) {
            for (let sx = 0; sx < ss; sx++) {
              const i = (((y * ss + sy) * cv.width) + (x * ss + sx)) * 4;
              const al = data[i + 3] / 255;
              r += data[i] * al; g += data[i + 1] * al; b += data[i + 2] * al; a += al;
            }
          }
          const n = ss * ss;
          if (a / n < alphaCut) { row += '.'; continue; }
          row += nearest(r / a, g / a, b / a);
        }
        rows.push(row);
      }
      out[name] = rows;
      report.push({
        name,
        source: `${img.naturalWidth}x${img.naturalHeight}`,
        cropped: `${cropW}x${cropH}`,
        result: `${targetW}x${targetH}`,
        replaced: !!existing,
        hadAlpha: opaque && (cropW < probe.width || cropH < probe.height),
      });
    }
    return { sprites: out, report };
  }, { dir: IN_DIR, names: files, alphaCut: ALPHA_CUT, ssMin: SS_MIN, forceHeight: heightArg });

  await browser.close();
  server.close();

  if (errors.length) {
    for (const e of errors) console.error(`  ! ${e.split('\n')[0]}`);
    process.exit(1);
  }

  await emit(result.sprites);

  console.log(`imported ${result.report.length} sprite(s) -> src/art/imported.js\n`);
  for (const r of result.report) {
    console.log(`  ${r.name.padEnd(18)} ${r.source.padEnd(11)} -> ${r.result.padEnd(9)}` +
      `${r.replaced ? ' (replaces existing)' : ' (new)'}`);
    if (!r.hadAlpha) {
      console.log('      ! no transparent margin found — if this has a background baked in,');
      console.log('        it will import as a rectangle. Ask for a transparent PNG.');
    }
  }
  console.log('\nnext: node tools/artsheet.mjs --only <names> --out shots/imported.png');
}

main().catch((err) => { console.error(err); process.exit(1); });
