// PNG -> palette-locked sprite importer.
//
//   node tools/importart.mjs               import everything in art-in/
//   node tools/importart.mjs --list        print every sprite name and its size
//   node tools/importart.mjs --height 32   override the target height
//
// Drop `art-in/<spriteName>.png` and this scales it to the size the game
// already uses for that sprite, box-filters it down, and snaps every pixel to
// the game palette. Output goes to src/art/imported.js as ordinary sprite rows,
// which override both the hand-authored and the vector-drawn versions.
//
// The palette snap is the whole point. Art from different sources — a different
// tool, a different day, a different model — arrives with its own colours, its
// own anti-aliasing and its own idea of contrast. Forcing it through one
// palette is what makes a jobsite look like one jobsite instead of a collage.

import { chromium } from 'playwright';
import { writeFile, readdir, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { serve } from './serve.mjs';
import { launchOptions } from './browser.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const IN_DIR = 'art-in';
const SS_MIN = 2;        // supersample at least this much before snapping
const ALPHA_CUT = 0.45;  // below this a pixel is transparent

const args = process.argv.slice(2);
const heightArg = args.includes('--height') ? Number(args[args.indexOf('--height') + 1]) : null;

/** The shopping list: what to name a file, and how big the game draws it. */
async function list() {
  const { ART } = await import('../src/art/sprites.js');
  const { SPRITES } = await import('../src/art/names.js');
  const { IMPORTED } = await import('../src/art/imported.js');
  console.log('name                 size      file to drop in art-in/');
  for (const name of SPRITES) {
    const rows = ART[name];
    const size = rows ? `${rows[0].length}x${rows.length}` : '?';
    const mark = IMPORTED[name] ? '  <- imported' : '';
    console.log(`  ${name.padEnd(18)} ${size.padEnd(9)} ${name}.png${mark}`);
  }
  console.log('\nAspect ratio is preserved — the height is what gets matched, so a wider');
  console.log('image just draws wider. Read art-in/README.md before generating anything.');
}

/** Write src/art/imported.js, empty or otherwise. */
async function emit(sprites) {
  const body = Object.entries(sprites)
    .map(([name, rows]) => `  ${name}: [\n${rows.map((r) => `    '${r}',`).join('\n')}\n  ],`)
    .join('\n');

  await writeFile(join(ROOT, 'src/art/imported.js'), `// GENERATED by tools/importart.mjs — do not edit by hand.
//
// Source images live in art-in/. Re-import with:
//
//   node tools/importart.mjs
//
// These override both hand-authored and vector-drawn sprites of the same name.
// Empty by default: the game ships entirely on art drawn in code, and this file
// only fills up if someone drops PNGs into art-in/.

export const IMPORTED = {
${body ? `${body}\n` : ''}};
`);
}

async function main() {
  if (args.includes('--list')) return list();

  await mkdir(join(ROOT, IN_DIR), { recursive: true });
  let files = [];
  try {
    files = (await readdir(join(ROOT, IN_DIR))).filter((f) => /\.png$/i.test(f));
  } catch { /* no directory yet */ }

  if (!files.length) {
    // Still write the file. Deleting a PNG and re-running has to actually undo
    // the import, or the game keeps drawing art whose source is gone.
    await emit({});
    console.log(`nothing to import: put <spriteName>.png files in ${IN_DIR}/`);
    console.log('see art-in/README.md for what the images need to look like');
    return;
  }

  const { server, port } = await serve(0);
  const browser = await chromium.launch(launchOptions());
  const page = await browser.newPage({ viewport: { width: 800, height: 600 } });
  const errors = [];
  page.on('pageerror', (e) => errors.push(String(e.stack || e)));

  await page.goto(`http://localhost:${port}/index.html`, { waitUntil: 'load' });

  const result = await page.evaluate(async ({ dir, names, alphaCut, ssMin, forceHeight }) => {
    const { PAL, ART } = await import('/src/art/sprites.js');
    const { snapper, imageToRows } = await import('/tools/quantise.js');
    const snap = snapper(PAL);

    const out = {};
    const report = [];
    for (const file of names) {
      const name = file.replace(/\.png$/i, '');
      // Target height: whatever the game already draws this sprite at, so an
      // import is a drop-in replacement and nothing downstream shifts.
      const existing = ART[name];
      const targetH = forceHeight || (existing ? existing.length : 24);
      const got = await imageToRows(`/${dir}/${file}`, { targetH, alphaCut, ssMin, snap });
      out[name] = got.rows;
      report.push({
        name,
        source: got.source,
        cropped: got.cropped,
        result: got.result,
        replaced: !!existing,
        hadAlpha: got.trimmed,
      });
    }
    return { sprites: out, report };
  }, { dir: IN_DIR, names: files, alphaCut: ALPHA_CUT, ssMin: SS_MIN, forceHeight: heightArg });

  await browser.close();
  server.close();

  if (errors.length) {
    for (const e of errors) console.error(`  ! ${e.split('\n')[0]}`);
    process.exit(1);
  }

  await emit(result.sprites);

  console.log(`imported ${result.report.length} sprite(s) -> src/art/imported.js\n`);
  for (const r of result.report) {
    console.log(`  ${r.name.padEnd(18)} ${r.source.padEnd(11)} -> ${r.result.padEnd(9)}` +
      `${r.replaced ? ' (replaces existing)' : ' (new)'}`);
    if (!r.hadAlpha) {
      console.log('      ! no transparent margin found — if this has a background baked in,');
      console.log('        it will import as a rectangle. Ask for a transparent PNG.');
    }
  }
  console.log('\nnext: node tools/artsheet.mjs --only <names> --out shots/imported.png');
}

main().catch((err) => { console.error(err); process.exit(1); });
